require("sjparker94.plugins-setup")

require("sjparker94.core.options")
require("sjparker94.core.keymaps")
require("sjparker94.core.colorscheme")

require("sjparker94.plugins.comment")
require("sjparker94.plugins.nvim-tree")
require("sjparker94.plugins.lualine")
require("sjparker94.plugins.telescope")
require("sjparker94.plugins.treesitter")
-- require("sjparker94.plugins.autopairs")
require("sjparker94.plugins.gitsigns")
require("sjparker94.plugins.harpoon")
require("sjparker94.plugins.undotree")
require("sjparker94.plugins.fugitive")

require("sjparker94.plugins.lsp.lsp")
require("sjparker94.plugins.lsp.lspsaga")
require("sjparker94.plugins.lsp.null-ls")
require("sjparker94.plugins.lsp.trouble")
